# Form implementation generated from reading ui file 'App_UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 992)
        MainWindow.setMaximumSize(QtCore.QSize(1199, 992))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 1199, 992))
        self.stackedWidget.setObjectName("stackedWidget")
        self.logo = QtWidgets.QWidget()
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(parent=self.logo)
        self.label.setGeometry(QtCore.QRect(0, 0, 1199, 992))
        self.label.setMaximumSize(QtCore.QSize(1199, 992))
        self.label.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Images/LOGO.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.logo)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 1199, 992))
        self.pushButton.setMaximumSize(QtCore.QSize(1199, 992))
        self.pushButton.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.logo)
        self.askTK = QtWidgets.QWidget()
        self.askTK.setMaximumSize(QtCore.QSize(1199, 992))
        self.askTK.setObjectName("askTK")
        self.label_2 = QtWidgets.QLabel(parent=self.askTK)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1199, 992))
        self.label_2.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Canva/Chọn.png"))
        self.label_2.setObjectName("label_2")
        self.btnYes = QtWidgets.QPushButton(parent=self.askTK)
        self.btnYes.setGeometry(QtCore.QRect(170, 620, 421, 151))
        self.btnYes.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnYes.setText("")
        self.btnYes.setObjectName("btnYes")
        self.btnNo = QtWidgets.QPushButton(parent=self.askTK)
        self.btnNo.setGeometry(QtCore.QRect(610, 620, 421, 151))
        self.btnNo.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnNo.setText("")
        self.btnNo.setObjectName("btnNo")
        self.stackedWidget.addWidget(self.askTK)
        self.LogIn = QtWidgets.QWidget()
        self.LogIn.setMaximumSize(QtCore.QSize(1199, 992))
        self.LogIn.setObjectName("LogIn")
        self.label_3 = QtWidgets.QLabel(parent=self.LogIn)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1199, 992))
        self.label_3.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Canva/Màn log in.png"))
        self.label_3.setObjectName("label_3")
        self.btnLogIn = QtWidgets.QPushButton(parent=self.LogIn)
        self.btnLogIn.setGeometry(QtCore.QRect(520, 750, 201, 111))
        self.btnLogIn.setMaximumSize(QtCore.QSize(201, 111))
        self.btnLogIn.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnLogIn.setText("")
        self.btnLogIn.setObjectName("btnLogIn")
        self.linUserName = QtWidgets.QLineEdit(parent=self.LogIn)
        self.linUserName.setGeometry(QtCore.QRect(400, 450, 441, 91))
        self.linUserName.setMaximumSize(QtCore.QSize(441, 91))
        self.linUserName.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.linUserName.setObjectName("linUserName")
        self.linePass = QtWidgets.QLineEdit(parent=self.LogIn)
        self.linePass.setGeometry(QtCore.QRect(400, 610, 441, 91))
        self.linePass.setMaximumSize(QtCore.QSize(441, 91))
        self.linePass.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.linePass.setObjectName("linePass")
        self.stackedWidget.addWidget(self.LogIn)
        self.SignUp = QtWidgets.QWidget()
        self.SignUp.setMaximumSize(QtCore.QSize(1199, 992))
        self.SignUp.setObjectName("SignUp")
        self.label_4 = QtWidgets.QLabel(parent=self.SignUp)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1199, 992))
        self.label_4.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Canva/Màn sign in.png"))
        self.label_4.setObjectName("label_4")
        self.lineUserName = QtWidgets.QLineEdit(parent=self.SignUp)
        self.lineUserName.setGeometry(QtCore.QRect(410, 410, 421, 91))
        self.lineUserName.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineUserName.setObjectName("lineUserName")
        self.linePassword = QtWidgets.QLineEdit(parent=self.SignUp)
        self.linePassword.setGeometry(QtCore.QRect(410, 530, 421, 91))
        self.linePassword.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.linePassword.setObjectName("linePassword")
        self.lineConfirm = QtWidgets.QLineEdit(parent=self.SignUp)
        self.lineConfirm.setGeometry(QtCore.QRect(410, 650, 421, 91))
        self.lineConfirm.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineConfirm.setObjectName("lineConfirm")
        self.btnSignup = QtWidgets.QPushButton(parent=self.SignUp)
        self.btnSignup.setGeometry(QtCore.QRect(550, 790, 141, 71))
        self.btnSignup.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnSignup.setText("")
        self.btnSignup.setObjectName("btnSignup")
        self.stackedWidget.addWidget(self.SignUp)
        self.GThieu1 = QtWidgets.QWidget()
        self.GThieu1.setMaximumSize(QtCore.QSize(1199, 992))
        self.GThieu1.setObjectName("GThieu1")
        self.label_5 = QtWidgets.QLabel(parent=self.GThieu1)
        self.label_5.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_5.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Canva/giới thiệu - công việc.png"))
        self.label_5.setObjectName("label_5")
        self.btnNext = QtWidgets.QPushButton(parent=self.GThieu1)
        self.btnNext.setGeometry(QtCore.QRect(1070, 830, 121, 91))
        self.btnNext.setMaximumSize(QtCore.QSize(121, 91))
        self.btnNext.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext.setText("")
        self.btnNext.setObjectName("btnNext")
        self.stackedWidget.addWidget(self.GThieu1)
        self.GThieu2 = QtWidgets.QWidget()
        self.GThieu2.setObjectName("GThieu2")
        self.label_6 = QtWidgets.QLabel(parent=self.GThieu2)
        self.label_6.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_6.setMaximumSize(QtCore.QSize(1199, 999))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Canva/giới thiệu - nky tam trang.png"))
        self.label_6.setObjectName("label_6")
        self.btnNext_2 = QtWidgets.QPushButton(parent=self.GThieu2)
        self.btnNext_2.setGeometry(QtCore.QRect(1080, 830, 101, 91))
        self.btnNext_2.setMaximumSize(QtCore.QSize(121, 91))
        self.btnNext_2.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_2.setText("")
        self.btnNext_2.setObjectName("btnNext_2")
        self.stackedWidget.addWidget(self.GThieu2)
        self.GThieu3 = QtWidgets.QWidget()
        self.GThieu3.setObjectName("GThieu3")
        self.label_7 = QtWidgets.QLabel(parent=self.GThieu3)
        self.label_7.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_7.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Canva/giới thịu thần số học.png"))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.GThieu3)
        self.pushButton_2.setGeometry(QtCore.QRect(1080, 830, 101, 91))
        self.pushButton_2.setMaximumSize(QtCore.QSize(121, 91))
        self.pushButton_2.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.GThieu3)
        self.Birthday = QtWidgets.QWidget()
        self.Birthday.setMaximumSize(QtCore.QSize(1199, 992))
        self.Birthday.setObjectName("Birthday")
        self.label_8 = QtWidgets.QLabel(parent=self.Birthday)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1199, 992))
        self.label_8.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../Canva/nhập ngày sinh.png"))
        self.label_8.setObjectName("label_8")
        self.day = QtWidgets.QLineEdit(parent=self.Birthday)
        self.day.setGeometry(QtCore.QRect(220, 350, 171, 151))
        self.day.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.day.setObjectName("day")
        self.month = QtWidgets.QLineEdit(parent=self.Birthday)
        self.month.setGeometry(QtCore.QRect(470, 350, 171, 151))
        self.month.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.month.setObjectName("month")
        self.year = QtWidgets.QLineEdit(parent=self.Birthday)
        self.year.setGeometry(QtCore.QRect(720, 350, 251, 151))
        self.year.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.year.setObjectName("year")
        self.btnDone = QtWidgets.QPushButton(parent=self.Birthday)
        self.btnDone.setGeometry(QtCore.QRect(430, 720, 341, 141))
        self.btnDone.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnDone.setText("")
        self.btnDone.setObjectName("btnDone")
        self.stackedWidget.addWidget(self.Birthday)
        self.Main = QtWidgets.QWidget()
        self.Main.setMaximumSize(QtCore.QSize(1199, 992))
        self.Main.setObjectName("Main")
        self.label_9 = QtWidgets.QLabel(parent=self.Main)
        self.label_9.setGeometry(QtCore.QRect(0, -30, 1199, 992))
        self.label_9.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../Canva/màn hình chính.png"))
        self.label_9.setObjectName("label_9")
        self.btnChooseToDoList = QtWidgets.QPushButton(parent=self.Main)
        self.btnChooseToDoList.setGeometry(QtCore.QRect(70, 180, 501, 131))
        self.btnChooseToDoList.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnChooseToDoList.setText("")
        self.btnChooseToDoList.setObjectName("btnChooseToDoList")
        self.btnChooseDiary = QtWidgets.QPushButton(parent=self.Main)
        self.btnChooseDiary.setGeometry(QtCore.QRect(630, 180, 501, 131))
        self.btnChooseDiary.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnChooseDiary.setText("")
        self.btnChooseDiary.setObjectName("btnChooseDiary")
        self.lineQuote = QtWidgets.QLineEdit(parent=self.Main)
        self.lineQuote.setGeometry(QtCore.QRect(70, 530, 1051, 201))
        self.lineQuote.setMaximumSize(QtCore.QSize(1051, 201))
        self.lineQuote.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineQuote.setObjectName("lineQuote")
        self.stackedWidget.addWidget(self.Main)
        self.ToDoList = QtWidgets.QWidget()
        self.ToDoList.setMaximumSize(QtCore.QSize(1199, 992))
        self.ToDoList.setObjectName("ToDoList")
        self.label_10 = QtWidgets.QLabel(parent=self.ToDoList)
        self.label_10.setGeometry(QtCore.QRect(10, -40, 1199, 992))
        self.label_10.setMaximumSize(QtCore.QSize(1199, 992))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setLineWidth(0)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../Canva/Việc cần làm.png"))
        self.label_10.setObjectName("label_10")
        self.btnAdd = QtWidgets.QPushButton(parent=self.ToDoList)
        self.btnAdd.setGeometry(QtCore.QRect(140, 100, 81, 81))
        self.btnAdd.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd.setText("")
        self.btnAdd.setObjectName("btnAdd")
        self.lineAdd = QtWidgets.QLineEdit(parent=self.ToDoList)
        self.lineAdd.setGeometry(QtCore.QRect(110, 210, 761, 111))
        self.lineAdd.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd.setObjectName("lineAdd")
        self.btnPre = QtWidgets.QPushButton(parent=self.ToDoList)
        self.btnPre.setGeometry(QtCore.QRect(30, 840, 91, 91))
        self.btnPre.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre.setText("")
        self.btnPre.setObjectName("btnPre")
        self.stackedWidget.addWidget(self.ToDoList)
        self.ToDoList_2 = QtWidgets.QWidget()
        self.ToDoList_2.setMaximumSize(QtCore.QSize(1199, 992))
        self.ToDoList_2.setObjectName("ToDoList_2")
        self.btnAdd_2 = QtWidgets.QPushButton(parent=self.ToDoList_2)
        self.btnAdd_2.setGeometry(QtCore.QRect(140, 140, 81, 81))
        self.btnAdd_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd_2.setText("")
        self.btnAdd_2.setObjectName("btnAdd_2")
        self.lineAdd_2 = QtWidgets.QLineEdit(parent=self.ToDoList_2)
        self.lineAdd_2.setGeometry(QtCore.QRect(110, 250, 761, 111))
        self.lineAdd_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_2.setObjectName("lineAdd_2")
        self.label_11 = QtWidgets.QLabel(parent=self.ToDoList_2)
        self.label_11.setGeometry(QtCore.QRect(10, -40, 1199, 992))
        self.label_11.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../Canva/Việc cần làm (2).png"))
        self.label_11.setObjectName("label_11")
        self.lineAdd_3 = QtWidgets.QLineEdit(parent=self.ToDoList_2)
        self.lineAdd_3.setGeometry(QtCore.QRect(110, 390, 761, 111))
        self.lineAdd_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_3.setObjectName("lineAdd_3")
        self.btnPre_2 = QtWidgets.QPushButton(parent=self.ToDoList_2)
        self.btnPre_2.setGeometry(QtCore.QRect(30, 840, 91, 91))
        self.btnPre_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_2.setText("")
        self.btnPre_2.setObjectName("btnPre_2")
        self.stackedWidget.addWidget(self.ToDoList_2)
        self.ToDoList_3 = QtWidgets.QWidget()
        self.ToDoList_3.setObjectName("ToDoList_3")
        self.btnAdd_3 = QtWidgets.QPushButton(parent=self.ToDoList_3)
        self.btnAdd_3.setGeometry(QtCore.QRect(150, 100, 81, 81))
        self.btnAdd_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd_3.setText("")
        self.btnAdd_3.setObjectName("btnAdd_3")
        self.lineAdd_4 = QtWidgets.QLineEdit(parent=self.ToDoList_3)
        self.lineAdd_4.setGeometry(QtCore.QRect(120, 210, 761, 111))
        self.lineAdd_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_4.setObjectName("lineAdd_4")
        self.lineAdd_5 = QtWidgets.QLineEdit(parent=self.ToDoList_3)
        self.lineAdd_5.setGeometry(QtCore.QRect(120, 350, 761, 111))
        self.lineAdd_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_5.setObjectName("lineAdd_5")
        self.label_12 = QtWidgets.QLabel(parent=self.ToDoList_3)
        self.label_12.setGeometry(QtCore.QRect(10, -40, 1199, 992))
        self.label_12.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../Canva/Việc cần làm (3).png"))
        self.label_12.setObjectName("label_12")
        self.lineAdd_6 = QtWidgets.QLineEdit(parent=self.ToDoList_3)
        self.lineAdd_6.setGeometry(QtCore.QRect(120, 500, 761, 111))
        self.lineAdd_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_6.setObjectName("lineAdd_6")
        self.btnPre_3 = QtWidgets.QPushButton(parent=self.ToDoList_3)
        self.btnPre_3.setGeometry(QtCore.QRect(30, 840, 91, 91))
        self.btnPre_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_3.setText("")
        self.btnPre_3.setObjectName("btnPre_3")
        self.stackedWidget.addWidget(self.ToDoList_3)
        self.ToDoList_4 = QtWidgets.QWidget()
        self.ToDoList_4.setObjectName("ToDoList_4")
        self.btnAdd_4 = QtWidgets.QPushButton(parent=self.ToDoList_4)
        self.btnAdd_4.setGeometry(QtCore.QRect(150, 110, 81, 81))
        self.btnAdd_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd_4.setText("")
        self.btnAdd_4.setObjectName("btnAdd_4")
        self.lineAdd_7 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_7.setGeometry(QtCore.QRect(120, 360, 761, 111))
        self.lineAdd_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_7.setObjectName("lineAdd_7")
        self.label_13 = QtWidgets.QLabel(parent=self.ToDoList_4)
        self.label_13.setGeometry(QtCore.QRect(10, -40, 1199, 992))
        self.label_13.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../Canva/Việc cần làm (4).png"))
        self.label_13.setObjectName("label_13")
        self.lineAdd_8 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_8.setGeometry(QtCore.QRect(120, 220, 761, 111))
        self.lineAdd_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_8.setObjectName("lineAdd_8")
        self.lineAdd_9 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_9.setGeometry(QtCore.QRect(120, 500, 761, 111))
        self.lineAdd_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_9.setObjectName("lineAdd_9")
        self.lineAdd_10 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_10.setGeometry(QtCore.QRect(130, 640, 761, 111))
        self.lineAdd_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_10.setObjectName("lineAdd_10")
        self.btnPre_4 = QtWidgets.QPushButton(parent=self.ToDoList_4)
        self.btnPre_4.setGeometry(QtCore.QRect(30, 840, 91, 91))
        self.btnPre_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_4.setText("")
        self.btnPre_4.setObjectName("btnPre_4")
        self.stackedWidget.addWidget(self.ToDoList_4)
        self.EmoOkay = QtWidgets.QWidget()
        self.EmoOkay.setMaximumSize(QtCore.QSize(1199, 992))
        self.EmoOkay.setObjectName("EmoOkay")
        self.label_14 = QtWidgets.QLabel(parent=self.EmoOkay)
        self.label_14.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_14.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../Canva/Ổn.png"))
        self.label_14.setObjectName("label_14")
        self.btnPre_5 = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnPre_5.setGeometry(QtCore.QRect(20, 840, 91, 81))
        self.btnPre_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_5.setText("")
        self.btnPre_5.setObjectName("btnPre_5")
        self.btnNext_3 = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnNext_3.setGeometry(QtCore.QRect(1090, 840, 91, 81))
        self.btnNext_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_3.setText("")
        self.btnNext_3.setObjectName("btnNext_3")
        self.btnDepressed = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnDepressed.setGeometry(QtCore.QRect(230, 680, 81, 71))
        self.btnDepressed.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed.setText("")
        self.btnDepressed.setObjectName("btnDepressed")
        self.btnSad = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnSad.setGeometry(QtCore.QRect(340, 680, 81, 71))
        self.btnSad.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad.setText("")
        self.btnSad.setObjectName("btnSad")
        self.btnAngry = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnAngry.setGeometry(QtCore.QRect(450, 680, 81, 71))
        self.btnAngry.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry.setText("")
        self.btnAngry.setObjectName("btnAngry")
        self.btnHappy = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnHappy.setGeometry(QtCore.QRect(670, 680, 81, 71))
        self.btnHappy.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy.setText("")
        self.btnHappy.setObjectName("btnHappy")
        self.btnExcited = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnExcited.setGeometry(QtCore.QRect(780, 680, 81, 71))
        self.btnExcited.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited.setText("")
        self.btnExcited.setObjectName("btnExcited")
        self.btnLove = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnLove.setGeometry(QtCore.QRect(890, 680, 81, 71))
        self.btnLove.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove.setText("")
        self.btnLove.setObjectName("btnLove")
        self.btnOkay = QtWidgets.QPushButton(parent=self.EmoOkay)
        self.btnOkay.setGeometry(QtCore.QRect(560, 680, 81, 71))
        self.btnOkay.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay.setText("")
        self.btnOkay.setObjectName("btnOkay")
        self.stackedWidget.addWidget(self.EmoOkay)
        self.EmoHappy = QtWidgets.QWidget()
        self.EmoHappy.setMaximumSize(QtCore.QSize(1199, 992))
        self.EmoHappy.setObjectName("EmoHappy")
        self.label_15 = QtWidgets.QLabel(parent=self.EmoHappy)
        self.label_15.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_15.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../Canva/Dui.png"))
        self.label_15.setObjectName("label_15")
        self.btnNext_4 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnNext_4.setGeometry(QtCore.QRect(1090, 840, 91, 81))
        self.btnNext_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_4.setText("")
        self.btnNext_4.setObjectName("btnNext_4")
        self.btnDepressed_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnDepressed_2.setGeometry(QtCore.QRect(230, 680, 81, 71))
        self.btnDepressed_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_2.setText("")
        self.btnDepressed_2.setObjectName("btnDepressed_2")
        self.btnAngry_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnAngry_2.setGeometry(QtCore.QRect(450, 680, 81, 71))
        self.btnAngry_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_2.setText("")
        self.btnAngry_2.setObjectName("btnAngry_2")
        self.btnOkay_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnOkay_2.setGeometry(QtCore.QRect(560, 680, 81, 71))
        self.btnOkay_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_2.setText("")
        self.btnOkay_2.setObjectName("btnOkay_2")
        self.btnSad_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnSad_2.setGeometry(QtCore.QRect(340, 680, 81, 71))
        self.btnSad_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_2.setText("")
        self.btnSad_2.setObjectName("btnSad_2")
        self.btnHappy_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnHappy_2.setGeometry(QtCore.QRect(670, 680, 81, 71))
        self.btnHappy_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_2.setText("")
        self.btnHappy_2.setObjectName("btnHappy_2")
        self.btnLove_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnLove_2.setGeometry(QtCore.QRect(890, 680, 81, 71))
        self.btnLove_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_2.setText("")
        self.btnLove_2.setObjectName("btnLove_2")
        self.btnPre_6 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnPre_6.setGeometry(QtCore.QRect(20, 840, 91, 81))
        self.btnPre_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_6.setText("")
        self.btnPre_6.setObjectName("btnPre_6")
        self.btnExcited_2 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnExcited_2.setGeometry(QtCore.QRect(780, 680, 81, 71))
        self.btnExcited_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_2.setText("")
        self.btnExcited_2.setObjectName("btnExcited_2")
        self.stackedWidget.addWidget(self.EmoHappy)
        self.EmoExcited = QtWidgets.QWidget()
        self.EmoExcited.setObjectName("EmoExcited")
        self.btnNext_5 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnNext_5.setGeometry(QtCore.QRect(1100, 840, 91, 81))
        self.btnNext_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_5.setText("")
        self.btnNext_5.setObjectName("btnNext_5")
        self.label_16 = QtWidgets.QLabel(parent=self.EmoExcited)
        self.label_16.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_16.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../Canva/Hào hứng.png"))
        self.label_16.setObjectName("label_16")
        self.btnSad_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnSad_3.setGeometry(QtCore.QRect(350, 680, 81, 71))
        self.btnSad_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_3.setText("")
        self.btnSad_3.setObjectName("btnSad_3")
        self.btnDepressed_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnDepressed_3.setGeometry(QtCore.QRect(240, 680, 81, 71))
        self.btnDepressed_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_3.setText("")
        self.btnDepressed_3.setObjectName("btnDepressed_3")
        self.btnHappy_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnHappy_3.setGeometry(QtCore.QRect(680, 680, 81, 71))
        self.btnHappy_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_3.setText("")
        self.btnHappy_3.setObjectName("btnHappy_3")
        self.btnAngry_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnAngry_3.setGeometry(QtCore.QRect(460, 680, 81, 71))
        self.btnAngry_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_3.setText("")
        self.btnAngry_3.setObjectName("btnAngry_3")
        self.btnExcited_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnExcited_3.setGeometry(QtCore.QRect(790, 680, 81, 71))
        self.btnExcited_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_3.setText("")
        self.btnExcited_3.setObjectName("btnExcited_3")
        self.btnOkay_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnOkay_3.setGeometry(QtCore.QRect(570, 680, 81, 71))
        self.btnOkay_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_3.setText("")
        self.btnOkay_3.setObjectName("btnOkay_3")
        self.btnPre_7 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnPre_7.setGeometry(QtCore.QRect(20, 840, 91, 81))
        self.btnPre_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_7.setText("")
        self.btnPre_7.setObjectName("btnPre_7")
        self.btnLove_3 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnLove_3.setGeometry(QtCore.QRect(900, 680, 81, 71))
        self.btnLove_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_3.setText("")
        self.btnLove_3.setObjectName("btnLove_3")
        self.stackedWidget.addWidget(self.EmoExcited)
        self.EmoLove = QtWidgets.QWidget()
        self.EmoLove.setObjectName("EmoLove")
        self.btnPre_8 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnPre_8.setGeometry(QtCore.QRect(10, 840, 91, 81))
        self.btnPre_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_8.setText("")
        self.btnPre_8.setObjectName("btnPre_8")
        self.btnNext_6 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnNext_6.setGeometry(QtCore.QRect(1090, 840, 91, 81))
        self.btnNext_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_6.setText("")
        self.btnNext_6.setObjectName("btnNext_6")
        self.btnAngry_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnAngry_4.setGeometry(QtCore.QRect(450, 680, 81, 71))
        self.btnAngry_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_4.setText("")
        self.btnAngry_4.setObjectName("btnAngry_4")
        self.btnLove_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnLove_4.setGeometry(QtCore.QRect(890, 680, 81, 71))
        self.btnLove_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_4.setText("")
        self.btnLove_4.setObjectName("btnLove_4")
        self.btnHappy_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnHappy_4.setGeometry(QtCore.QRect(670, 680, 81, 71))
        self.btnHappy_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_4.setText("")
        self.btnHappy_4.setObjectName("btnHappy_4")
        self.btnDepressed_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnDepressed_4.setGeometry(QtCore.QRect(230, 680, 81, 71))
        self.btnDepressed_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_4.setText("")
        self.btnDepressed_4.setObjectName("btnDepressed_4")
        self.label_17 = QtWidgets.QLabel(parent=self.EmoLove)
        self.label_17.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_17.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../Canva/iu đời.png"))
        self.label_17.setObjectName("label_17")
        self.btnExcited_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnExcited_4.setGeometry(QtCore.QRect(780, 680, 81, 71))
        self.btnExcited_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_4.setText("")
        self.btnExcited_4.setObjectName("btnExcited_4")
        self.btnOkay_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnOkay_4.setGeometry(QtCore.QRect(560, 680, 81, 71))
        self.btnOkay_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_4.setText("")
        self.btnOkay_4.setObjectName("btnOkay_4")
        self.btnSad_4 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnSad_4.setGeometry(QtCore.QRect(340, 680, 81, 71))
        self.btnSad_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_4.setText("")
        self.btnSad_4.setObjectName("btnSad_4")
        self.stackedWidget.addWidget(self.EmoLove)
        self.EmoAngry = QtWidgets.QWidget()
        self.EmoAngry.setObjectName("EmoAngry")
        self.btnPre_9 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnPre_9.setGeometry(QtCore.QRect(10, 840, 91, 81))
        self.btnPre_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_9.setText("")
        self.btnPre_9.setObjectName("btnPre_9")
        self.btnHappy_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnHappy_5.setGeometry(QtCore.QRect(670, 680, 81, 71))
        self.btnHappy_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_5.setText("")
        self.btnHappy_5.setObjectName("btnHappy_5")
        self.btnAngry_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnAngry_5.setGeometry(QtCore.QRect(450, 680, 81, 71))
        self.btnAngry_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_5.setText("")
        self.btnAngry_5.setObjectName("btnAngry_5")
        self.btnLove_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnLove_5.setGeometry(QtCore.QRect(890, 680, 81, 71))
        self.btnLove_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_5.setText("")
        self.btnLove_5.setObjectName("btnLove_5")
        self.btnSad_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnSad_5.setGeometry(QtCore.QRect(340, 680, 81, 71))
        self.btnSad_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_5.setText("")
        self.btnSad_5.setObjectName("btnSad_5")
        self.btnExcited_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnExcited_5.setGeometry(QtCore.QRect(780, 680, 81, 71))
        self.btnExcited_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_5.setText("")
        self.btnExcited_5.setObjectName("btnExcited_5")
        self.btnDepressed_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnDepressed_5.setGeometry(QtCore.QRect(230, 680, 81, 71))
        self.btnDepressed_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_5.setText("")
        self.btnDepressed_5.setObjectName("btnDepressed_5")
        self.label_18 = QtWidgets.QLabel(parent=self.EmoAngry)
        self.label_18.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_18.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../Canva/cọc.png"))
        self.label_18.setObjectName("label_18")
        self.btnNext_7 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnNext_7.setGeometry(QtCore.QRect(1090, 840, 91, 81))
        self.btnNext_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_7.setText("")
        self.btnNext_7.setObjectName("btnNext_7")
        self.btnOkay_5 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnOkay_5.setGeometry(QtCore.QRect(560, 680, 81, 71))
        self.btnOkay_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_5.setText("")
        self.btnOkay_5.setObjectName("btnOkay_5")
        self.stackedWidget.addWidget(self.EmoAngry)
        self.EmoSad = QtWidgets.QWidget()
        self.EmoSad.setObjectName("EmoSad")
        self.btnPre_10 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnPre_10.setGeometry(QtCore.QRect(10, 840, 91, 81))
        self.btnPre_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_10.setText("")
        self.btnPre_10.setObjectName("btnPre_10")
        self.btnNext_8 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnNext_8.setGeometry(QtCore.QRect(1090, 840, 91, 81))
        self.btnNext_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_8.setText("")
        self.btnNext_8.setObjectName("btnNext_8")
        self.btnOkay_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnOkay_6.setGeometry(QtCore.QRect(560, 680, 81, 71))
        self.btnOkay_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_6.setText("")
        self.btnOkay_6.setObjectName("btnOkay_6")
        self.btnHappy_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnHappy_6.setGeometry(QtCore.QRect(670, 680, 81, 71))
        self.btnHappy_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_6.setText("")
        self.btnHappy_6.setObjectName("btnHappy_6")
        self.btnDepressed_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnDepressed_6.setGeometry(QtCore.QRect(230, 680, 81, 71))
        self.btnDepressed_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_6.setText("")
        self.btnDepressed_6.setObjectName("btnDepressed_6")
        self.btnSad_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnSad_6.setGeometry(QtCore.QRect(340, 680, 81, 71))
        self.btnSad_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_6.setText("")
        self.btnSad_6.setObjectName("btnSad_6")
        self.btnAngry_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnAngry_6.setGeometry(QtCore.QRect(450, 680, 81, 71))
        self.btnAngry_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_6.setText("")
        self.btnAngry_6.setObjectName("btnAngry_6")
        self.label_19 = QtWidgets.QLabel(parent=self.EmoSad)
        self.label_19.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_19.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../Canva/buồn ó.png"))
        self.label_19.setObjectName("label_19")
        self.btnExcited_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnExcited_6.setGeometry(QtCore.QRect(780, 680, 81, 71))
        self.btnExcited_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_6.setText("")
        self.btnExcited_6.setObjectName("btnExcited_6")
        self.btnLove_6 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnLove_6.setGeometry(QtCore.QRect(890, 680, 81, 71))
        self.btnLove_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_6.setText("")
        self.btnLove_6.setObjectName("btnLove_6")
        self.stackedWidget.addWidget(self.EmoSad)
        self.EmoDepressed = QtWidgets.QWidget()
        self.EmoDepressed.setObjectName("EmoDepressed")
        self.btnSad_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnSad_7.setGeometry(QtCore.QRect(340, 680, 81, 71))
        self.btnSad_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_7.setText("")
        self.btnSad_7.setObjectName("btnSad_7")
        self.btnAngry_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnAngry_7.setGeometry(QtCore.QRect(450, 680, 81, 71))
        self.btnAngry_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_7.setText("")
        self.btnAngry_7.setObjectName("btnAngry_7")
        self.btnOkay_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnOkay_7.setGeometry(QtCore.QRect(560, 680, 81, 71))
        self.btnOkay_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_7.setText("")
        self.btnOkay_7.setObjectName("btnOkay_7")
        self.label_20 = QtWidgets.QLabel(parent=self.EmoDepressed)
        self.label_20.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_20.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("../Canva/skibidi dom dom yes yes.png"))
        self.label_20.setObjectName("label_20")
        self.btnLove_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnLove_7.setGeometry(QtCore.QRect(890, 680, 81, 71))
        self.btnLove_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_7.setText("")
        self.btnLove_7.setObjectName("btnLove_7")
        self.btnHappy_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnHappy_7.setGeometry(QtCore.QRect(670, 680, 81, 71))
        self.btnHappy_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_7.setText("")
        self.btnHappy_7.setObjectName("btnHappy_7")
        self.btnExcited_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnExcited_7.setGeometry(QtCore.QRect(780, 680, 81, 71))
        self.btnExcited_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_7.setText("")
        self.btnExcited_7.setObjectName("btnExcited_7")
        self.btnNext_9 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnNext_9.setGeometry(QtCore.QRect(1090, 840, 91, 81))
        self.btnNext_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_9.setText("")
        self.btnNext_9.setObjectName("btnNext_9")
        self.btnDepressed_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnDepressed_7.setGeometry(QtCore.QRect(230, 680, 81, 71))
        self.btnDepressed_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_7.setText("")
        self.btnDepressed_7.setObjectName("btnDepressed_7")
        self.btnPre_11 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnPre_11.setGeometry(QtCore.QRect(10, 840, 91, 81))
        self.btnPre_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_11.setText("")
        self.btnPre_11.setObjectName("btnPre_11")
        self.stackedWidget.addWidget(self.EmoDepressed)
        self.Diary = QtWidgets.QWidget()
        self.Diary.setMaximumSize(QtCore.QSize(1199, 992))
        self.Diary.setObjectName("Diary")
        self.label_21 = QtWidgets.QLabel(parent=self.Diary)
        self.label_21.setGeometry(QtCore.QRect(0, -50, 1199, 992))
        self.label_21.setMaximumSize(QtCore.QSize(1199, 992))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../Canva/21.png"))
        self.label_21.setObjectName("label_21")
        self.txtDiary = QtWidgets.QTextEdit(parent=self.Diary)
        self.txtDiary.setGeometry(QtCore.QRect(160, 160, 881, 681))
        self.txtDiary.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.txtDiary.setObjectName("txtDiary")
        self.btnNext_10 = QtWidgets.QPushButton(parent=self.Diary)
        self.btnNext_10.setGeometry(QtCore.QRect(1100, 840, 91, 81))
        self.btnNext_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;\n"
"")
        self.btnNext_10.setText("")
        self.btnNext_10.setObjectName("btnNext_10")
        self.stackedWidget.addWidget(self.Diary)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1199, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
