# Form implementation generated from reading ui file 'App_UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 750)
        MainWindow.setMaximumSize(QtCore.QSize(906, 750))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(906, 750))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 906, 750))
        self.stackedWidget.setMaximumSize(QtCore.QSize(906, 750))
        self.stackedWidget.setObjectName("stackedWidget")
        self.logo = QtWidgets.QWidget()
        self.logo.setMaximumSize(QtCore.QSize(1199, 800))
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(parent=self.logo)
        self.label.setGeometry(QtCore.QRect(10, 0, 906, 750))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(906, 750))
        self.label.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Images/LOGO.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.logo)
        self.pushButton.setGeometry(QtCore.QRect(-410, 80, 906, 750))
        self.pushButton.setMaximumSize(QtCore.QSize(906, 750))
        self.pushButton.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.logo)
        self.askTK = QtWidgets.QWidget()
        self.askTK.setMaximumSize(QtCore.QSize(906, 750))
        self.askTK.setObjectName("askTK")
        self.label_2 = QtWidgets.QLabel(parent=self.askTK)
        self.label_2.setGeometry(QtCore.QRect(0, -50, 906, 800))
        self.label_2.setMaximumSize(QtCore.QSize(906, 850))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Images/Chọn.png"))
        self.label_2.setObjectName("label_2")
        self.btnYes = QtWidgets.QPushButton(parent=self.askTK)
        self.btnYes.setGeometry(QtCore.QRect(140, 450, 311, 101))
        self.btnYes.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnYes.setText("")
        self.btnYes.setObjectName("btnYes")
        self.btnNo = QtWidgets.QPushButton(parent=self.askTK)
        self.btnNo.setGeometry(QtCore.QRect(470, 450, 291, 101))
        self.btnNo.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnNo.setText("")
        self.btnNo.setObjectName("btnNo")
        self.stackedWidget.addWidget(self.askTK)
        self.LogIn = QtWidgets.QWidget()
        self.LogIn.setMaximumSize(QtCore.QSize(906, 750))
        self.LogIn.setObjectName("LogIn")
        self.label_3 = QtWidgets.QLabel(parent=self.LogIn)
        self.label_3.setGeometry(QtCore.QRect(0, -30, 906, 750))
        self.label_3.setMaximumSize(QtCore.QSize(906, 750))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Images/Màn log in.png"))
        self.label_3.setObjectName("label_3")
        self.btnLogIn = QtWidgets.QPushButton(parent=self.LogIn)
        self.btnLogIn.setGeometry(QtCore.QRect(400, 550, 141, 61))
        self.btnLogIn.setMaximumSize(QtCore.QSize(201, 111))
        self.btnLogIn.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnLogIn.setText("")
        self.btnLogIn.setObjectName("btnLogIn")
        self.lineUserName_2 = QtWidgets.QLineEdit(parent=self.LogIn)
        self.lineUserName_2.setGeometry(QtCore.QRect(310, 320, 311, 61))
        self.lineUserName_2.setMaximumSize(QtCore.QSize(441, 91))
        self.lineUserName_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineUserName_2.setObjectName("lineUserName_2")
        self.linePass = QtWidgets.QLineEdit(parent=self.LogIn)
        self.linePass.setGeometry(QtCore.QRect(310, 440, 321, 51))
        self.linePass.setMaximumSize(QtCore.QSize(441, 91))
        self.linePass.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.linePass.setObjectName("linePass")
        self.stackedWidget.addWidget(self.LogIn)
        self.SignUp = QtWidgets.QWidget()
        self.SignUp.setMaximumSize(QtCore.QSize(906, 750))
        self.SignUp.setObjectName("SignUp")
        self.label_4 = QtWidgets.QLabel(parent=self.SignUp)
        self.label_4.setGeometry(QtCore.QRect(10, -20, 906, 750))
        self.label_4.setMaximumSize(QtCore.QSize(906, 750))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Images/Màn sign in.png"))
        self.label_4.setObjectName("label_4")
        self.lineUserName = QtWidgets.QLineEdit(parent=self.SignUp)
        self.lineUserName.setGeometry(QtCore.QRect(330, 300, 291, 51))
        self.lineUserName.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineUserName.setObjectName("lineUserName")
        self.linePassword = QtWidgets.QLineEdit(parent=self.SignUp)
        self.linePassword.setGeometry(QtCore.QRect(330, 390, 291, 51))
        self.linePassword.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.linePassword.setObjectName("linePassword")
        self.lineConfirm = QtWidgets.QLineEdit(parent=self.SignUp)
        self.lineConfirm.setGeometry(QtCore.QRect(330, 480, 291, 51))
        self.lineConfirm.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineConfirm.setObjectName("lineConfirm")
        self.btnSignup = QtWidgets.QPushButton(parent=self.SignUp)
        self.btnSignup.setGeometry(QtCore.QRect(430, 580, 91, 51))
        self.btnSignup.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnSignup.setText("")
        self.btnSignup.setObjectName("btnSignup")
        self.stackedWidget.addWidget(self.SignUp)
        self.GThieu1 = QtWidgets.QWidget()
        self.GThieu1.setMaximumSize(QtCore.QSize(906, 750))
        self.GThieu1.setObjectName("GThieu1")
        self.label_5 = QtWidgets.QLabel(parent=self.GThieu1)
        self.label_5.setGeometry(QtCore.QRect(0, -40, 903, 750))
        self.label_5.setMaximumSize(QtCore.QSize(906, 750))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Images/giới thiệu - công việc.png"))
        self.label_5.setObjectName("label_5")
        self.btnNext = QtWidgets.QPushButton(parent=self.GThieu1)
        self.btnNext.setGeometry(QtCore.QRect(800, 620, 93, 71))
        self.btnNext.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext.setText("")
        self.btnNext.setObjectName("btnNext")
        self.stackedWidget.addWidget(self.GThieu1)
        self.GThieu2 = QtWidgets.QWidget()
        self.GThieu2.setMaximumSize(QtCore.QSize(906, 750))
        self.GThieu2.setObjectName("GThieu2")
        self.label_6 = QtWidgets.QLabel(parent=self.GThieu2)
        self.label_6.setGeometry(QtCore.QRect(10, -90, 1199, 850))
        self.label_6.setMaximumSize(QtCore.QSize(1199, 850))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Images/giới thiệu - nky tam trang.png"))
        self.label_6.setObjectName("label_6")
        self.btnNext_2 = QtWidgets.QPushButton(parent=self.GThieu2)
        self.btnNext_2.setGeometry(QtCore.QRect(810, 620, 93, 81))
        self.btnNext_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_2.setText("")
        self.btnNext_2.setObjectName("btnNext_2")
        self.stackedWidget.addWidget(self.GThieu2)
        self.GThieu3 = QtWidgets.QWidget()
        self.GThieu3.setMaximumSize(QtCore.QSize(906, 750))
        self.GThieu3.setObjectName("GThieu3")
        self.label_7 = QtWidgets.QLabel(parent=self.GThieu3)
        self.label_7.setGeometry(QtCore.QRect(10, -30, 906, 750))
        self.label_7.setMaximumSize(QtCore.QSize(906, 750))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Images/giới thịu thần số học.png"))
        self.label_7.setObjectName("label_7")
        self.btnNext_11 = QtWidgets.QPushButton(parent=self.GThieu3)
        self.btnNext_11.setGeometry(QtCore.QRect(810, 630, 93, 71))
        self.btnNext_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_11.setText("")
        self.btnNext_11.setObjectName("btnNext_11")
        self.stackedWidget.addWidget(self.GThieu3)
        self.Birthday = QtWidgets.QWidget()
        self.Birthday.setMaximumSize(QtCore.QSize(906, 750))
        self.Birthday.setObjectName("Birthday")
        self.label_8 = QtWidgets.QLabel(parent=self.Birthday)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 906, 750))
        self.label_8.setMaximumSize(QtCore.QSize(906, 750))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../Images/nhập ngày sinh.png"))
        self.label_8.setObjectName("label_8")
        self.day = QtWidgets.QLineEdit(parent=self.Birthday)
        self.day.setGeometry(QtCore.QRect(190, 270, 111, 111))
        self.day.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.day.setObjectName("day")
        self.month = QtWidgets.QLineEdit(parent=self.Birthday)
        self.month.setGeometry(QtCore.QRect(370, 270, 121, 101))
        self.month.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.month.setObjectName("month")
        self.year = QtWidgets.QLineEdit(parent=self.Birthday)
        self.year.setGeometry(QtCore.QRect(560, 270, 181, 111))
        self.year.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.year.setObjectName("year")
        self.btnDone = QtWidgets.QPushButton(parent=self.Birthday)
        self.btnDone.setGeometry(QtCore.QRect(330, 540, 271, 111))
        self.btnDone.setStyleSheet("color: rgb(0,0,0);\n"
"border:None;")
        self.btnDone.setText("")
        self.btnDone.setObjectName("btnDone")
        self.stackedWidget.addWidget(self.Birthday)
        self.Main = QtWidgets.QWidget()
        self.Main.setMaximumSize(QtCore.QSize(906, 750))
        self.Main.setObjectName("Main")
        self.label_9 = QtWidgets.QLabel(parent=self.Main)
        self.label_9.setGeometry(QtCore.QRect(0, -30, 906, 750))
        self.label_9.setMaximumSize(QtCore.QSize(906, 750))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../Images/màn hình chính.png"))
        self.label_9.setObjectName("label_9")
        self.btnChooseToDoList = QtWidgets.QPushButton(parent=self.Main)
        self.btnChooseToDoList.setGeometry(QtCore.QRect(60, 130, 351, 91))
        self.btnChooseToDoList.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnChooseToDoList.setText("")
        self.btnChooseToDoList.setObjectName("btnChooseToDoList")
        self.btnChooseDiary = QtWidgets.QPushButton(parent=self.Main)
        self.btnChooseDiary.setGeometry(QtCore.QRect(480, 130, 361, 91))
        self.btnChooseDiary.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnChooseDiary.setText("")
        self.btnChooseDiary.setObjectName("btnChooseDiary")
        self.lineQuote = QtWidgets.QLineEdit(parent=self.Main)
        self.lineQuote.setGeometry(QtCore.QRect(60, 400, 791, 151))
        self.lineQuote.setMaximumSize(QtCore.QSize(1051, 201))
        self.lineQuote.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineQuote.setObjectName("lineQuote")
        self.stackedWidget.addWidget(self.Main)
        self.ToDoList = QtWidgets.QWidget()
        self.ToDoList.setMaximumSize(QtCore.QSize(906, 750))
        self.ToDoList.setObjectName("ToDoList")
        self.label_10 = QtWidgets.QLabel(parent=self.ToDoList)
        self.label_10.setGeometry(QtCore.QRect(10, -30, 906, 750))
        self.label_10.setMaximumSize(QtCore.QSize(906, 750))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setLineWidth(0)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../Images/Việc cần làm.png"))
        self.label_10.setObjectName("label_10")
        self.btnAdd = QtWidgets.QPushButton(parent=self.ToDoList)
        self.btnAdd.setGeometry(QtCore.QRect(100, 70, 81, 81))
        self.btnAdd.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd.setText("")
        self.btnAdd.setObjectName("btnAdd")
        self.lineAdd = QtWidgets.QLineEdit(parent=self.ToDoList)
        self.lineAdd.setGeometry(QtCore.QRect(100, 170, 561, 71))
        self.lineAdd.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd.setObjectName("lineAdd")
        self.btnPre = QtWidgets.QPushButton(parent=self.ToDoList)
        self.btnPre.setGeometry(QtCore.QRect(20, 640, 81, 61))
        self.btnPre.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre.setText("")
        self.btnPre.setObjectName("btnPre")
        self.stackedWidget.addWidget(self.ToDoList)
        self.ToDoList_2 = QtWidgets.QWidget()
        self.ToDoList_2.setMaximumSize(QtCore.QSize(906, 750))
        self.ToDoList_2.setObjectName("ToDoList_2")
        self.btnAdd_2 = QtWidgets.QPushButton(parent=self.ToDoList_2)
        self.btnAdd_2.setGeometry(QtCore.QRect(110, 70, 71, 71))
        self.btnAdd_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd_2.setText("")
        self.btnAdd_2.setObjectName("btnAdd_2")
        self.lineAdd_2 = QtWidgets.QLineEdit(parent=self.ToDoList_2)
        self.lineAdd_2.setGeometry(QtCore.QRect(90, 170, 571, 61))
        self.lineAdd_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_2.setObjectName("lineAdd_2")
        self.label_11 = QtWidgets.QLabel(parent=self.ToDoList_2)
        self.label_11.setGeometry(QtCore.QRect(10, -30, 906, 750))
        self.label_11.setMaximumSize(QtCore.QSize(906, 750))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../Images/Việc cần làm (2).png"))
        self.label_11.setObjectName("label_11")
        self.lineAdd_3 = QtWidgets.QLineEdit(parent=self.ToDoList_2)
        self.lineAdd_3.setGeometry(QtCore.QRect(90, 280, 571, 51))
        self.lineAdd_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_3.setObjectName("lineAdd_3")
        self.btnPre_2 = QtWidgets.QPushButton(parent=self.ToDoList_2)
        self.btnPre_2.setGeometry(QtCore.QRect(20, 630, 81, 71))
        self.btnPre_2.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_2.setText("")
        self.btnPre_2.setObjectName("btnPre_2")
        self.label_11.raise_()
        self.btnAdd_2.raise_()
        self.lineAdd_2.raise_()
        self.lineAdd_3.raise_()
        self.btnPre_2.raise_()
        self.stackedWidget.addWidget(self.ToDoList_2)
        self.ToDoList_3 = QtWidgets.QWidget()
        self.ToDoList_3.setMaximumSize(QtCore.QSize(906, 750))
        self.ToDoList_3.setObjectName("ToDoList_3")
        self.btnAdd_3 = QtWidgets.QPushButton(parent=self.ToDoList_3)
        self.btnAdd_3.setGeometry(QtCore.QRect(100, 70, 81, 81))
        self.btnAdd_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd_3.setText("")
        self.btnAdd_3.setObjectName("btnAdd_3")
        self.lineAdd_4 = QtWidgets.QLineEdit(parent=self.ToDoList_3)
        self.lineAdd_4.setGeometry(QtCore.QRect(100, 170, 561, 61))
        self.lineAdd_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_4.setObjectName("lineAdd_4")
        self.lineAdd_5 = QtWidgets.QLineEdit(parent=self.ToDoList_3)
        self.lineAdd_5.setGeometry(QtCore.QRect(100, 280, 561, 61))
        self.lineAdd_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_5.setObjectName("lineAdd_5")
        self.label_12 = QtWidgets.QLabel(parent=self.ToDoList_3)
        self.label_12.setGeometry(QtCore.QRect(10, -30, 906, 750))
        self.label_12.setMaximumSize(QtCore.QSize(906, 750))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../Images/Việc cần làm (3).png"))
        self.label_12.setObjectName("label_12")
        self.lineAdd_6 = QtWidgets.QLineEdit(parent=self.ToDoList_3)
        self.lineAdd_6.setGeometry(QtCore.QRect(100, 400, 561, 51))
        self.lineAdd_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_6.setObjectName("lineAdd_6")
        self.btnPre_3 = QtWidgets.QPushButton(parent=self.ToDoList_3)
        self.btnPre_3.setGeometry(QtCore.QRect(10, 630, 101, 81))
        self.btnPre_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_3.setText("")
        self.btnPre_3.setObjectName("btnPre_3")
        self.label_12.raise_()
        self.btnAdd_3.raise_()
        self.lineAdd_4.raise_()
        self.lineAdd_5.raise_()
        self.lineAdd_6.raise_()
        self.btnPre_3.raise_()
        self.stackedWidget.addWidget(self.ToDoList_3)
        self.ToDoList_4 = QtWidgets.QWidget()
        self.ToDoList_4.setMaximumSize(QtCore.QSize(906, 750))
        self.ToDoList_4.setObjectName("ToDoList_4")
        self.btnAdd_4 = QtWidgets.QPushButton(parent=self.ToDoList_4)
        self.btnAdd_4.setGeometry(QtCore.QRect(110, 70, 81, 81))
        self.btnAdd_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAdd_4.setText("")
        self.btnAdd_4.setObjectName("btnAdd_4")
        self.lineAdd_7 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_7.setGeometry(QtCore.QRect(100, 280, 571, 71))
        self.lineAdd_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_7.setObjectName("lineAdd_7")
        self.label_13 = QtWidgets.QLabel(parent=self.ToDoList_4)
        self.label_13.setGeometry(QtCore.QRect(10, -30, 906, 750))
        self.label_13.setMaximumSize(QtCore.QSize(906, 750))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../Images/Việc cần làm (4).png"))
        self.label_13.setObjectName("label_13")
        self.lineAdd_8 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_8.setGeometry(QtCore.QRect(100, 170, 571, 61))
        self.lineAdd_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_8.setObjectName("lineAdd_8")
        self.lineAdd_9 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_9.setGeometry(QtCore.QRect(100, 390, 571, 51))
        self.lineAdd_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_9.setObjectName("lineAdd_9")
        self.lineAdd_10 = QtWidgets.QLineEdit(parent=self.ToDoList_4)
        self.lineAdd_10.setGeometry(QtCore.QRect(100, 500, 571, 61))
        self.lineAdd_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.lineAdd_10.setObjectName("lineAdd_10")
        self.btn_Pre = QtWidgets.QPushButton(parent=self.ToDoList_4)
        self.btn_Pre.setGeometry(QtCore.QRect(20, 630, 91, 71))
        self.btn_Pre.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btn_Pre.setText("")
        self.btn_Pre.setObjectName("btn_Pre")
        self.label_13.raise_()
        self.btnAdd_4.raise_()
        self.lineAdd_7.raise_()
        self.lineAdd_8.raise_()
        self.lineAdd_9.raise_()
        self.lineAdd_10.raise_()
        self.btn_Pre.raise_()
        self.stackedWidget.addWidget(self.ToDoList_4)
        self.EmoOkay = QtWidgets.QWidget()
        self.EmoOkay.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoOkay.setObjectName("EmoOkay")
        self.label_14 = QtWidgets.QLabel(parent=self.EmoOkay)
        self.label_14.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_14.setMaximumSize(QtCore.QSize(906, 750))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("../Images/Ổn.png"))
        self.label_14.setObjectName("label_14")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.EmoOkay)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 490, 561, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(27)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLove = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnLove.setMinimumSize(QtCore.QSize(50, 50))
        self.btnLove.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove.setText("")
        self.btnLove.setObjectName("btnLove")
        self.horizontalLayout.addWidget(self.btnLove)
        self.btnHappy = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnHappy.setMinimumSize(QtCore.QSize(50, 50))
        self.btnHappy.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy.setText("")
        self.btnHappy.setObjectName("btnHappy")
        self.horizontalLayout.addWidget(self.btnHappy)
        self.btnExcited = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnExcited.setMinimumSize(QtCore.QSize(50, 50))
        self.btnExcited.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited.setText("")
        self.btnExcited.setObjectName("btnExcited")
        self.horizontalLayout.addWidget(self.btnExcited)
        self.btnOkay = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnOkay.setMinimumSize(QtCore.QSize(50, 50))
        self.btnOkay.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay.setText("")
        self.btnOkay.setObjectName("btnOkay")
        self.horizontalLayout.addWidget(self.btnOkay)
        self.btnAngry = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnAngry.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAngry.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry.setText("")
        self.btnAngry.setObjectName("btnAngry")
        self.horizontalLayout.addWidget(self.btnAngry)
        self.btnSad = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnSad.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSad.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad.setText("")
        self.btnSad.setObjectName("btnSad")
        self.horizontalLayout.addWidget(self.btnSad)
        self.btnDepressed = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnDepressed.setMinimumSize(QtCore.QSize(50, 50))
        self.btnDepressed.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed.setText("")
        self.btnDepressed.setObjectName("btnDepressed")
        self.horizontalLayout.addWidget(self.btnDepressed)
        self.stackedWidget.addWidget(self.EmoOkay)
        self.EmoHappy = QtWidgets.QWidget()
        self.EmoHappy.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoHappy.setObjectName("EmoHappy")
        self.label_15 = QtWidgets.QLabel(parent=self.EmoHappy)
        self.label_15.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_15.setMaximumSize(QtCore.QSize(906, 750))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../Images/Dui.png"))
        self.label_15.setObjectName("label_15")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.EmoHappy)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(180, 490, 561, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(27)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnLove_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnLove_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnLove_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_8.setText("")
        self.btnLove_8.setObjectName("btnLove_8")
        self.horizontalLayout_3.addWidget(self.btnLove_8)
        self.btnHappy_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnHappy_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnHappy_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_8.setText("")
        self.btnHappy_8.setObjectName("btnHappy_8")
        self.horizontalLayout_3.addWidget(self.btnHappy_8)
        self.btnExcited_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnExcited_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnExcited_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_8.setText("")
        self.btnExcited_8.setObjectName("btnExcited_8")
        self.horizontalLayout_3.addWidget(self.btnExcited_8)
        self.btnOkay_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnOkay_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnOkay_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_8.setText("")
        self.btnOkay_8.setObjectName("btnOkay_8")
        self.horizontalLayout_3.addWidget(self.btnOkay_8)
        self.btnAngry_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnAngry_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAngry_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_8.setText("")
        self.btnAngry_8.setObjectName("btnAngry_8")
        self.horizontalLayout_3.addWidget(self.btnAngry_8)
        self.btnSad_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnSad_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSad_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_8.setText("")
        self.btnSad_8.setObjectName("btnSad_8")
        self.horizontalLayout_3.addWidget(self.btnSad_8)
        self.btnDepressed_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnDepressed_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btnDepressed_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_8.setText("")
        self.btnDepressed_8.setObjectName("btnDepressed_8")
        self.horizontalLayout_3.addWidget(self.btnDepressed_8)
        self.btnPre_4 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnPre_4.setGeometry(QtCore.QRect(20, 610, 91, 71))
        self.btnPre_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_4.setText("")
        self.btnPre_4.setObjectName("btnPre_4")
        self.btnNext_3 = QtWidgets.QPushButton(parent=self.EmoHappy)
        self.btnNext_3.setGeometry(QtCore.QRect(820, 610, 91, 71))
        self.btnNext_3.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_3.setText("")
        self.btnNext_3.setObjectName("btnNext_3")
        self.stackedWidget.addWidget(self.EmoHappy)
        self.EmoExcited = QtWidgets.QWidget()
        self.EmoExcited.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoExcited.setObjectName("EmoExcited")
        self.label_16 = QtWidgets.QLabel(parent=self.EmoExcited)
        self.label_16.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_16.setMaximumSize(QtCore.QSize(906, 750))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("../Images/Hào hứng.png"))
        self.label_16.setObjectName("label_16")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.EmoExcited)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(170, 490, 561, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(27)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLove_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnLove_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btnLove_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_9.setText("")
        self.btnLove_9.setObjectName("btnLove_9")
        self.horizontalLayout_4.addWidget(self.btnLove_9)
        self.btnHappy_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnHappy_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btnHappy_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_9.setText("")
        self.btnHappy_9.setObjectName("btnHappy_9")
        self.horizontalLayout_4.addWidget(self.btnHappy_9)
        self.btnExcited_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnExcited_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btnExcited_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_9.setText("")
        self.btnExcited_9.setObjectName("btnExcited_9")
        self.horizontalLayout_4.addWidget(self.btnExcited_9)
        self.btnOkay_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnOkay_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btnOkay_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_9.setText("")
        self.btnOkay_9.setObjectName("btnOkay_9")
        self.horizontalLayout_4.addWidget(self.btnOkay_9)
        self.btnAngry_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnAngry_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_9.setText("")
        self.btnAngry_9.setObjectName("btnAngry_9")
        self.horizontalLayout_4.addWidget(self.btnAngry_9)
        self.btnSad_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnSad_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSad_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_9.setText("")
        self.btnSad_9.setObjectName("btnSad_9")
        self.horizontalLayout_4.addWidget(self.btnSad_9)
        self.btnDepressed_9 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnDepressed_9.setMinimumSize(QtCore.QSize(50, 50))
        self.btnDepressed_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_9.setText("")
        self.btnDepressed_9.setObjectName("btnDepressed_9")
        self.horizontalLayout_4.addWidget(self.btnDepressed_9)
        self.btnNext_4 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnNext_4.setGeometry(QtCore.QRect(810, 620, 91, 71))
        self.btnNext_4.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_4.setText("")
        self.btnNext_4.setObjectName("btnNext_4")
        self.btnPre_5 = QtWidgets.QPushButton(parent=self.EmoExcited)
        self.btnPre_5.setGeometry(QtCore.QRect(10, 620, 91, 71))
        self.btnPre_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_5.setText("")
        self.btnPre_5.setObjectName("btnPre_5")
        self.stackedWidget.addWidget(self.EmoExcited)
        self.EmoLove = QtWidgets.QWidget()
        self.EmoLove.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoLove.setObjectName("EmoLove")
        self.label_17 = QtWidgets.QLabel(parent=self.EmoLove)
        self.label_17.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_17.setMaximumSize(QtCore.QSize(906, 750))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../Images/iu đời.png"))
        self.label_17.setObjectName("label_17")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(parent=self.EmoLove)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(180, 490, 561, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(27)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnLove_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnLove_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnLove_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_10.setText("")
        self.btnLove_10.setObjectName("btnLove_10")
        self.horizontalLayout_5.addWidget(self.btnLove_10)
        self.btnHappy_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnHappy_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnHappy_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_10.setText("")
        self.btnHappy_10.setObjectName("btnHappy_10")
        self.horizontalLayout_5.addWidget(self.btnHappy_10)
        self.btnExcited_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnExcited_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnExcited_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_10.setText("")
        self.btnExcited_10.setObjectName("btnExcited_10")
        self.horizontalLayout_5.addWidget(self.btnExcited_10)
        self.btnOkay_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnOkay_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnOkay_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_10.setText("")
        self.btnOkay_10.setObjectName("btnOkay_10")
        self.horizontalLayout_5.addWidget(self.btnOkay_10)
        self.btnAngry_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnAngry_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAngry_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_10.setText("")
        self.btnAngry_10.setObjectName("btnAngry_10")
        self.horizontalLayout_5.addWidget(self.btnAngry_10)
        self.btnSad_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnSad_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSad_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_10.setText("")
        self.btnSad_10.setObjectName("btnSad_10")
        self.horizontalLayout_5.addWidget(self.btnSad_10)
        self.btnDepressed_10 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_5)
        self.btnDepressed_10.setMinimumSize(QtCore.QSize(50, 50))
        self.btnDepressed_10.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_10.setText("")
        self.btnDepressed_10.setObjectName("btnDepressed_10")
        self.horizontalLayout_5.addWidget(self.btnDepressed_10)
        self.btnNext_5 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnNext_5.setGeometry(QtCore.QRect(820, 630, 91, 71))
        self.btnNext_5.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_5.setText("")
        self.btnNext_5.setObjectName("btnNext_5")
        self.btnPre_6 = QtWidgets.QPushButton(parent=self.EmoLove)
        self.btnPre_6.setGeometry(QtCore.QRect(20, 630, 91, 71))
        self.btnPre_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_6.setText("")
        self.btnPre_6.setObjectName("btnPre_6")
        self.stackedWidget.addWidget(self.EmoLove)
        self.EmoAngry = QtWidgets.QWidget()
        self.EmoAngry.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoAngry.setObjectName("EmoAngry")
        self.label_18 = QtWidgets.QLabel(parent=self.EmoAngry)
        self.label_18.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_18.setMaximumSize(QtCore.QSize(906, 750))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("../Images/cọc.png"))
        self.label_18.setObjectName("label_18")
        self.btnPre_7 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnPre_7.setGeometry(QtCore.QRect(10, 620, 91, 71))
        self.btnPre_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_7.setText("")
        self.btnPre_7.setObjectName("btnPre_7")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(parent=self.EmoAngry)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(170, 490, 561, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(27)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnLove_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnLove_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnLove_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_11.setText("")
        self.btnLove_11.setObjectName("btnLove_11")
        self.horizontalLayout_6.addWidget(self.btnLove_11)
        self.btnHappy_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnHappy_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnHappy_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_11.setText("")
        self.btnHappy_11.setObjectName("btnHappy_11")
        self.horizontalLayout_6.addWidget(self.btnHappy_11)
        self.btnExcited_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnExcited_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnExcited_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_11.setText("")
        self.btnExcited_11.setObjectName("btnExcited_11")
        self.horizontalLayout_6.addWidget(self.btnExcited_11)
        self.btnOkay_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnOkay_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnOkay_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_11.setText("")
        self.btnOkay_11.setObjectName("btnOkay_11")
        self.horizontalLayout_6.addWidget(self.btnOkay_11)
        self.btnAngry_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnAngry_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAngry_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_11.setText("")
        self.btnAngry_11.setObjectName("btnAngry_11")
        self.horizontalLayout_6.addWidget(self.btnAngry_11)
        self.btnSad_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnSad_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSad_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_11.setText("")
        self.btnSad_11.setObjectName("btnSad_11")
        self.horizontalLayout_6.addWidget(self.btnSad_11)
        self.btnDepressed_11 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_6)
        self.btnDepressed_11.setMinimumSize(QtCore.QSize(50, 50))
        self.btnDepressed_11.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_11.setText("")
        self.btnDepressed_11.setObjectName("btnDepressed_11")
        self.horizontalLayout_6.addWidget(self.btnDepressed_11)
        self.btnNext_6 = QtWidgets.QPushButton(parent=self.EmoAngry)
        self.btnNext_6.setGeometry(QtCore.QRect(810, 620, 91, 71))
        self.btnNext_6.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_6.setText("")
        self.btnNext_6.setObjectName("btnNext_6")
        self.stackedWidget.addWidget(self.EmoAngry)
        self.EmoSad = QtWidgets.QWidget()
        self.EmoSad.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoSad.setObjectName("EmoSad")
        self.label_19 = QtWidgets.QLabel(parent=self.EmoSad)
        self.label_19.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_19.setMaximumSize(QtCore.QSize(906, 750))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("../Images/buồn ó.png"))
        self.label_19.setObjectName("label_19")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(parent=self.EmoSad)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(170, 490, 561, 80))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(27)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnLove_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnLove_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnLove_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_13.setText("")
        self.btnLove_13.setObjectName("btnLove_13")
        self.horizontalLayout_8.addWidget(self.btnLove_13)
        self.btnHappy_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnHappy_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnHappy_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_13.setText("")
        self.btnHappy_13.setObjectName("btnHappy_13")
        self.horizontalLayout_8.addWidget(self.btnHappy_13)
        self.btnExcited_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnExcited_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnExcited_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_13.setText("")
        self.btnExcited_13.setObjectName("btnExcited_13")
        self.horizontalLayout_8.addWidget(self.btnExcited_13)
        self.btnOkay_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnOkay_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnOkay_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_13.setText("")
        self.btnOkay_13.setObjectName("btnOkay_13")
        self.horizontalLayout_8.addWidget(self.btnOkay_13)
        self.btnAngry_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnAngry_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnAngry_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_13.setText("")
        self.btnAngry_13.setObjectName("btnAngry_13")
        self.horizontalLayout_8.addWidget(self.btnAngry_13)
        self.btnSad_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnSad_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnSad_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_13.setText("")
        self.btnSad_13.setObjectName("btnSad_13")
        self.horizontalLayout_8.addWidget(self.btnSad_13)
        self.btnDepressed_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_8)
        self.btnDepressed_13.setMinimumSize(QtCore.QSize(50, 50))
        self.btnDepressed_13.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_13.setText("")
        self.btnDepressed_13.setObjectName("btnDepressed_13")
        self.horizontalLayout_8.addWidget(self.btnDepressed_13)
        self.btnNext_9 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnNext_9.setGeometry(QtCore.QRect(810, 610, 91, 71))
        self.btnNext_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_9.setText("")
        self.btnNext_9.setObjectName("btnNext_9")
        self.btnPre_9 = QtWidgets.QPushButton(parent=self.EmoSad)
        self.btnPre_9.setGeometry(QtCore.QRect(10, 610, 91, 71))
        self.btnPre_9.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_9.setText("")
        self.btnPre_9.setObjectName("btnPre_9")
        self.stackedWidget.addWidget(self.EmoSad)
        self.EmoDepressed = QtWidgets.QWidget()
        self.EmoDepressed.setMaximumSize(QtCore.QSize(906, 750))
        self.EmoDepressed.setObjectName("EmoDepressed")
        self.label_20 = QtWidgets.QLabel(parent=self.EmoDepressed)
        self.label_20.setGeometry(QtCore.QRect(0, -50, 906, 750))
        self.label_20.setMaximumSize(QtCore.QSize(906, 750))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("../Images/skibidi dom dom yes yes.png"))
        self.label_20.setObjectName("label_20")
        self.btnNext_7 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnNext_7.setGeometry(QtCore.QRect(810, 620, 91, 71))
        self.btnNext_7.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_7.setText("")
        self.btnNext_7.setObjectName("btnNext_7")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(parent=self.EmoDepressed)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(170, 490, 561, 80))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(27)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnLove_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnLove_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnLove_12.setText("")
        self.btnLove_12.setObjectName("btnLove_12")
        self.horizontalLayout_7.addWidget(self.btnLove_12)
        self.btnHappy_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnHappy_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnHappy_12.setText("")
        self.btnHappy_12.setObjectName("btnHappy_12")
        self.horizontalLayout_7.addWidget(self.btnHappy_12)
        self.btnExcited_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnExcited_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnExcited_12.setText("")
        self.btnExcited_12.setObjectName("btnExcited_12")
        self.horizontalLayout_7.addWidget(self.btnExcited_12)
        self.btnOkay_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnOkay_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnOkay_12.setText("")
        self.btnOkay_12.setObjectName("btnOkay_12")
        self.horizontalLayout_7.addWidget(self.btnOkay_12)
        self.btnAngry_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnAngry_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnAngry_12.setText("")
        self.btnAngry_12.setObjectName("btnAngry_12")
        self.horizontalLayout_7.addWidget(self.btnAngry_12)
        self.btnSad_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnSad_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnSad_12.setText("")
        self.btnSad_12.setObjectName("btnSad_12")
        self.horizontalLayout_7.addWidget(self.btnSad_12)
        self.btnDepressed_12 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_7)
        self.btnDepressed_12.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnDepressed_12.setText("")
        self.btnDepressed_12.setObjectName("btnDepressed_12")
        self.horizontalLayout_7.addWidget(self.btnDepressed_12)
        self.btnPre_8 = QtWidgets.QPushButton(parent=self.EmoDepressed)
        self.btnPre_8.setGeometry(QtCore.QRect(10, 620, 91, 71))
        self.btnPre_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnPre_8.setText("")
        self.btnPre_8.setObjectName("btnPre_8")
        self.stackedWidget.addWidget(self.EmoDepressed)
        self.Diary = QtWidgets.QWidget()
        self.Diary.setMaximumSize(QtCore.QSize(906, 750))
        self.Diary.setObjectName("Diary")
        self.label_21 = QtWidgets.QLabel(parent=self.Diary)
        self.label_21.setGeometry(QtCore.QRect(10, -50, 906, 750))
        self.label_21.setMaximumSize(QtCore.QSize(906, 750))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../Images/21.png"))
        self.label_21.setObjectName("label_21")
        self.txtDiary = QtWidgets.QTextEdit(parent=self.Diary)
        self.txtDiary.setGeometry(QtCore.QRect(140, 110, 671, 501))
        self.txtDiary.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.txtDiary.setObjectName("txtDiary")
        self.btnNext_8 = QtWidgets.QPushButton(parent=self.Diary)
        self.btnNext_8.setGeometry(QtCore.QRect(820, 620, 91, 71))
        self.btnNext_8.setStyleSheet("background-color: rgb(255,128,145,0);\n"
"color: rgb(0,0,0);\n"
"border:None;")
        self.btnNext_8.setText("")
        self.btnNext_8.setObjectName("btnNext_8")
        self.stackedWidget.addWidget(self.Diary)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(20)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
